### PR TITLE
training docs translated in zh_cn(simplified Chinese/Mandarin) translation

### PR DESCRIPTION
**Pull request by Jjing-Liang**
Hi,
We have completed the Chinese translation, which basically maintains the exact same structure and naming as IT. 
Although the images have not been translated yet, we still keep the references to the images in the translation.
Meanwhile, I would like to ask if we can add a paragraph somewhere to thank the 9 people involved in the translation?

If you have any questions, please feel free to leave a comment, either to me or @Irenia111, thanks!

### CODE REVIEW

**Comment by russelltrow** [comment]
Hi @Jjing-Liang, one of our volunteers has reviewed the translations and provided their feedback. Could you please review the comments and make any changes as you think relevant.

Thank you

**Comment by Jjing-Liang** [comment]
Sure, I will make changes and let you know. Thanks for the review.

**Comment by Jjing-Liang** [comment]
Hi @russelltrow @binbinzhangSiemens 
Thanks for all the suggestions!
I made the changes and added a commit, please feel free to review them and leave comments.

**Comment by russelltrow** [comment]
@greenhsu123 can you please have a final review and confirm if you are happy for this PR to be merged?

**Comment by greenhsu123** [comment]
Approve! 謝謝 @Jjing-Liang for translating and @binbinzhangSiemens reviewing!

**Comment by Jjing-Liang** [comment]
🎉🎉
Thanks @russelltrow @greenhsu123 @binbinzhangSiemens  for all the support and for considering our request!

Also thank all of our team members from Thoughtworks for their contributions to the translation: @Irenia111, Rui Bian, QunYao Cai, Xiantong Cheng, Ying Fu, Aifei Lu, Guanyun Lu(malbona) and Zhaosen Wen.

**Comment by russelltrow** [comment]
Hi @Jjing-Liang, now that the PR has been approved could you please just follow the steps to sign-off your commit and pass the DCO check:

https://github.com/Green-Software-Foundation/learn/pull/207/checks?check_run_id=21261709434

**Comment by russelltrow** [comment]
Hi @Jjing-Liang I've just been testing the translation locally and raised a PR with a few amendments: https://github.com/Jjing-Liang/gsf-training/pull/1

**Pull request merged**
