### PR TITLE
First draft of french translation

### PR DESCRIPTION
**Pull request by llhardy1A**
Provide a french translation.
For now, on 2024-06-20, only one file has been processed in draft mode.
Important notes:
I wasn't able to test locally. For any reason, I have an error with yarn.
I will need also the original images and potentially some tips to update them.
Update:
Local test works
Still need full review, mainly glossary so to have coherent terms everywhere and also update images containing text.

### CODE REVIEW

**Comment by llhardy1A** [comment]
Hi all,
As of today, need a full review, in particular to agree on the glossary and adjust of course in all pages accordingly.
Need also to update images.

**Comment by russelltrow** [comment]
Hey @llhardy1A I've just tested the translations locally and it works perfectly.

@Jenya-design are you able to provide Leila access to the Green Software Practitioner course images please

Let me know what other support you need to complete it.

**Comment by Jenya-design** [comment]
Hi @llhardy1A 

Please check [this canva file](http://please%20make%20a%20copy%20before%20you%20start%20translation/), it contains all the images with editable text from the Green Software Practitioner course. 
Please make a copy of the file before you start translation. Images without text are not included, but  you can take those directly from the course. Let me know when you finish the translation - I can go through the slides and adjust the design
Do you need my help with anything else?

cc @russelltrow

**Comment by llhardy1A** [comment]
> Hey @llhardy1A I've just tested the translations locally and it works perfectly.
> 
> @Jenya-design are you able to provide Leila access to the Green Software Practitioner course images please
> 
> Let me know what other support you need to complete it.

Hi Russel,
Just saw your comment! I apologize but after my 2 weeks vacation in August, I wasn't able to attend to regular meeting and I'm afraid that I will not be able to attend to the next one.
Anyway, I have some good news about the translation as I found some support within Amadeus to put in place a glossary. Now come the difficult part :) which is to report choosen translation within my PR. 
I will let you know once it is ready.
Regards

**Comment by russelltrow** [comment]
The translations works perfectly. Thank you @llhardy1A and team so much for all your efforts!

**Pull request merged**
