### PR TITLE
Update introduction.md - run and build changed to build and run

### PR DESCRIPTION
**Pull request by imhamad**
Content flow error "run and build" should be "build and run"

### CODE REVIEW

**Comment by imhamad** [comment]
@franziska-warncke , would you mind taking a look

**Review by franziska-warncke — APPROVED** [review]
Nice catch!

**Comment by franziska-warncke** [comment]
@russelltrow Can you also have a look and merge it?

**Comment by imhamad** [comment]
Thank you, Franziska!

Really appreciate your comment on it!


From: Franziska Warncke ***@***.***>
Date: Monday, 22 July 2024 at 12:16 PM
To: Green-Software-Foundation/learn ***@***.***>
Cc: Hamad ***@***.***>, Author ***@***.***>
Subject: Re: [Green-Software-Foundation/learn] Update introduction.md - run and build changed to build and run (PR #234)

@franziska-warncke approved this pull request.

Nice catch!

**Comment by franziska-warncke** [comment]
Of course 👍

**Pull request merged**
